/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardWalkInRouteImport } from './routes/dashboard.walk-in'
import { Route as DashboardTokensRouteImport } from './routes/dashboard.tokens'
import { Route as DashboardSimulationRouteImport } from './routes/dashboard.simulation'
import { Route as DashboardSignageRouteImport } from './routes/dashboard.signage'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardQueueRouteImport } from './routes/dashboard.queue'
import { Route as DashboardPatientStatusRouteImport } from './routes/dashboard.patient-status'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardKioskRouteImport } from './routes/dashboard.kiosk'
import { Route as DashboardHelpRouteImport } from './routes/dashboard.help'
import { Route as DashboardDoctorsRouteImport } from './routes/dashboard.doctors'
import { Route as DashboardComplaintsRouteImport } from './routes/dashboard.complaints'
import { Route as DashboardAuditRouteImport } from './routes/dashboard.audit'
import { Route as DashboardAppointmentsRouteImport } from './routes/dashboard.appointments'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWalkInRoute = DashboardWalkInRouteImport.update({
  id: '/walk-in',
  path: '/walk-in',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTokensRoute = DashboardTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSimulationRoute = DashboardSimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSignageRoute = DashboardSignageRouteImport.update({
  id: '/signage',
  path: '/signage',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQueueRoute = DashboardQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPatientStatusRoute = DashboardPatientStatusRouteImport.update({
  id: '/patient-status',
  path: '/patient-status',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKioskRoute = DashboardKioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHelpRoute = DashboardHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDoctorsRoute = DashboardDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardComplaintsRoute = DashboardComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditRoute = DashboardAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppointmentsRoute = DashboardAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/complaints': typeof DashboardComplaintsRoute
  '/dashboard/doctors': typeof DashboardDoctorsRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/kiosk': typeof DashboardKioskRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/patient-status': typeof DashboardPatientStatusRoute
  '/dashboard/queue': typeof DashboardQueueRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/signage': typeof DashboardSignageRoute
  '/dashboard/simulation': typeof DashboardSimulationRoute
  '/dashboard/tokens': typeof DashboardTokensRoute
  '/dashboard/walk-in': typeof DashboardWalkInRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/complaints': typeof DashboardComplaintsRoute
  '/dashboard/doctors': typeof DashboardDoctorsRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/kiosk': typeof DashboardKioskRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/patient-status': typeof DashboardPatientStatusRoute
  '/dashboard/queue': typeof DashboardQueueRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/signage': typeof DashboardSignageRoute
  '/dashboard/simulation': typeof DashboardSimulationRoute
  '/dashboard/tokens': typeof DashboardTokensRoute
  '/dashboard/walk-in': typeof DashboardWalkInRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/complaints': typeof DashboardComplaintsRoute
  '/dashboard/doctors': typeof DashboardDoctorsRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/kiosk': typeof DashboardKioskRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/patient-status': typeof DashboardPatientStatusRoute
  '/dashboard/queue': typeof DashboardQueueRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/signage': typeof DashboardSignageRoute
  '/dashboard/simulation': typeof DashboardSimulationRoute
  '/dashboard/tokens': typeof DashboardTokensRoute
  '/dashboard/walk-in': typeof DashboardWalkInRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard/analytics'
    | '/dashboard/appointments'
    | '/dashboard/audit'
    | '/dashboard/complaints'
    | '/dashboard/doctors'
    | '/dashboard/help'
    | '/dashboard/kiosk'
    | '/dashboard/notifications'
    | '/dashboard/patient-status'
    | '/dashboard/queue'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/signage'
    | '/dashboard/simulation'
    | '/dashboard/tokens'
    | '/dashboard/walk-in'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard/analytics'
    | '/dashboard/appointments'
    | '/dashboard/audit'
    | '/dashboard/complaints'
    | '/dashboard/doctors'
    | '/dashboard/help'
    | '/dashboard/kiosk'
    | '/dashboard/notifications'
    | '/dashboard/patient-status'
    | '/dashboard/queue'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/signage'
    | '/dashboard/simulation'
    | '/dashboard/tokens'
    | '/dashboard/walk-in'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard/analytics'
    | '/dashboard/appointments'
    | '/dashboard/audit'
    | '/dashboard/complaints'
    | '/dashboard/doctors'
    | '/dashboard/help'
    | '/dashboard/kiosk'
    | '/dashboard/notifications'
    | '/dashboard/patient-status'
    | '/dashboard/queue'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/signage'
    | '/dashboard/simulation'
    | '/dashboard/tokens'
    | '/dashboard/walk-in'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/walk-in': {
      id: '/dashboard/walk-in'
      path: '/walk-in'
      fullPath: '/dashboard/walk-in'
      preLoaderRoute: typeof DashboardWalkInRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tokens': {
      id: '/dashboard/tokens'
      path: '/tokens'
      fullPath: '/dashboard/tokens'
      preLoaderRoute: typeof DashboardTokensRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/simulation': {
      id: '/dashboard/simulation'
      path: '/simulation'
      fullPath: '/dashboard/simulation'
      preLoaderRoute: typeof DashboardSimulationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/signage': {
      id: '/dashboard/signage'
      path: '/signage'
      fullPath: '/dashboard/signage'
      preLoaderRoute: typeof DashboardSignageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/queue': {
      id: '/dashboard/queue'
      path: '/queue'
      fullPath: '/dashboard/queue'
      preLoaderRoute: typeof DashboardQueueRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patient-status': {
      id: '/dashboard/patient-status'
      path: '/patient-status'
      fullPath: '/dashboard/patient-status'
      preLoaderRoute: typeof DashboardPatientStatusRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/kiosk': {
      id: '/dashboard/kiosk'
      path: '/kiosk'
      fullPath: '/dashboard/kiosk'
      preLoaderRoute: typeof DashboardKioskRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/help': {
      id: '/dashboard/help'
      path: '/help'
      fullPath: '/dashboard/help'
      preLoaderRoute: typeof DashboardHelpRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctors': {
      id: '/dashboard/doctors'
      path: '/doctors'
      fullPath: '/dashboard/doctors'
      preLoaderRoute: typeof DashboardDoctorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/complaints': {
      id: '/dashboard/complaints'
      path: '/complaints'
      fullPath: '/dashboard/complaints'
      preLoaderRoute: typeof DashboardComplaintsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audit': {
      id: '/dashboard/audit'
      path: '/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof DashboardAuditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/appointments': {
      id: '/dashboard/appointments'
      path: '/appointments'
      fullPath: '/dashboard/appointments'
      preLoaderRoute: typeof DashboardAppointmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardAppointmentsRoute: typeof DashboardAppointmentsRoute
  DashboardAuditRoute: typeof DashboardAuditRoute
  DashboardComplaintsRoute: typeof DashboardComplaintsRoute
  DashboardDoctorsRoute: typeof DashboardDoctorsRoute
  DashboardHelpRoute: typeof DashboardHelpRoute
  DashboardKioskRoute: typeof DashboardKioskRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardPatientStatusRoute: typeof DashboardPatientStatusRoute
  DashboardQueueRoute: typeof DashboardQueueRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSignageRoute: typeof DashboardSignageRoute
  DashboardSimulationRoute: typeof DashboardSimulationRoute
  DashboardTokensRoute: typeof DashboardTokensRoute
  DashboardWalkInRoute: typeof DashboardWalkInRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardAppointmentsRoute: DashboardAppointmentsRoute,
  DashboardAuditRoute: DashboardAuditRoute,
  DashboardComplaintsRoute: DashboardComplaintsRoute,
  DashboardDoctorsRoute: DashboardDoctorsRoute,
  DashboardHelpRoute: DashboardHelpRoute,
  DashboardKioskRoute: DashboardKioskRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardPatientStatusRoute: DashboardPatientStatusRoute,
  DashboardQueueRoute: DashboardQueueRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSignageRoute: DashboardSignageRoute,
  DashboardSimulationRoute: DashboardSimulationRoute,
  DashboardTokensRoute: DashboardTokensRoute,
  DashboardWalkInRoute: DashboardWalkInRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
